services:
  - type: web
    name: mim-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
