services:
  - type: web
    name: mim-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
      - key: WEBFLOW_WEBHOOK_SECRET
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: saNOTIFICATION_FROM_EMAIL
        sync: false
      - key: NOTIFICATION_FROM_NAME
        value: "MIM Marketplace"
      - key: EVOLUTION_API_URL
        sync: false
      - key: EVOLUTION_API_KEY
        sync: false
      - key: EVOLUTION_INSTANCE_NAME
        sync: false
      - key: CHATAPI_URL
        sync: false
      - key: CHATAPI_INSTANCE_ID
        sync: false
      - key: CHATAPI_TOKEN
        sync: false
      - key: WHATSAPP_WEBHOOK_URL
        sync: false
      - key: WHATSAPP_DEFAULT_COUNTRY_CODE
        value: "+212"
    healthCheckPath: /health
